const maps = [
    [       
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXX         XX              XX        XX      XXXXX",
        "XXXXX         XX      XX      XX        XX      XXXXX",
        "XXXXX         XX      XX      XX        XX      XXXXX",
        "XXXXX         XX      XX      XX        XX      XXXXX",
        "XXXXX         XX      XX      XX        XX      XXXXX",
        "XXXXX         XX      X       XX        XX      XXXXX",
        "XXXXX         XXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXX",
        "XXXXX         XXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXX",
        "XXXXXXXXXXXX XXX      X                 XX      XXXXX",
        "XXXXXXXXXXXX XXX      XX      XX        XX      XXXXX",
        "XXXXX         XX      XX      XX        XX      XXXXX",
        "XXXXX         XX      XX      XX        XX      XXXXX",
        "XXXXX         XX              XX                XXXXX",
        "XXXXX         XX      XX      XX        XX      XXXXX",
        "XXXXX         XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXX         XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXX XXXXXXX       XX       XX      XX      XXXXX",
        "XXXXXXXX XXXXXXX       XX       XX      XX      XXXXX",
        "XXXXX         XX       XX       XX      XX      XXXXX",
        "XXXXX         XX                        XX      XXXXX",
        "XXXXX         XX       XX       XX      XX      XXXXX",
        "XXXXX         XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX",
        "XXXXX         XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX",
        "XXXXXXXXXXXXX XX        XX      XX      XX      XXXXX",
        "XXXXXXXXXXXXX XX        XX      XX      XX      XXXXX",
        "XXXXX         XX        XX      XX              XXXXX",
        "XXXXX         XX        XX              XX      XXXXX",
        "XXXXX         XX                XX      XX      XXXXX",
        "XXXXX         XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXX         XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXX                            XX     XX      XXXXX",
        "XXXXX         XX          XX            XX      XXXXX",
        "XXXXX         XX          XX     XX     XX      XXXXX",
        "XXXXXXX XXXXXXXX          XX     XX     XX      XXXXX",
        "XXXXXXX XXXXXXXX          XX     XX     XX      XXXXX",
        "XXXXX         XX          XX     XX     XX      XXXXX",
        "XXXXX         XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX",
        "XXXXX         XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX",
        "XXXXX         XX          XX     XX     XX      XXXXX",
        "XXXXX         XX          XX     XX     XX      XXXXX",
        "XXXXX         XX          XX     XX     XX      XXXXX",
        "XXXXX         XX          XX     XX     XX      XXXXX",
        "XXXXX         XX                                XXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      ],
    [
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "X      XX      XX     XX       XX     XX    X",
        "X      XX      XX     XX       XX     XX    X",
        "X      XX      XX     XX       XX           X",
        "X      XX      XX     XX       XX     XX    X",
        "X      XX      XX     XX       XX     XX    X",
        "XXXXX XXXX XXXXXX     XX       XX     XX    X",
        "XXXXX XXXX XXXXXXXXX XXX       XXXXXXXXXXX XX",
        "X      XX         XX XXX          XXXXXXXX XX",
        "X      XX      XX        XXXXXXXX    XX     X",
        "X      XX      XX     XX XXXXXXXX    XX     X",
        "X      XX      XX     XX       XX    XX     X",
        "X      XX      XX     XX       XX    XX     X",
        "XX XXXXXXX XXXXXX     XX       XX    XX     X",
        "XX XXXXXXX XXXXXXXX XXXX       XX    XX     X",
        "X      XX      XXXX XXXXXXXXX XXX    XX     X",
        "X              XX     XXXXXXX XXX XXXXX     X",
        "X      XX      XX     XX       XX XXXXX     X",
        "X      XX      XX     XX       XX    XX     X",
        "X      XX      XX     XX       XX    XXX XXXX",
        "X      XX      XX     XX       XX    XXX XXXX",
        "X XXXXXXX XXXXXXX     XX       XX    XX     X",
        "X XXXXXXX XXXXXXX     XXXXXXXX XX    XX     X",
        "X      XX      XXXXXX XXXXXXXX XX    XX     X",
        "X      XX      XXXXXX XX       XX    XX     X",
        "X      XX      XX     XX       XXXX         X",
        "X      XX      XX     XX       XXXX XXX     X",
        "X      XX      XX     XX       XX    XXXX XXX",
        "X      XXXX XXXXX     XX       XX    XXXX XXX",
        "X      XXXX XXXXX     XX       XX    XX     X",
        "X      XX      XX     XX       XX    XX     X",
        "X      XX      XX     XX       XX    XX     X",
        "XXXX XXXX      XXXXX XXX       XX    XX     X",
        "XXXX XXXX      XXXXX XXXXX XXXXXX    XX     X",
        "X      XX      XX     XXXX XXXXXX    XX     X",
        "X      XX      XX     XX       XX XXXXXXXXXXX",
        "X      XXXXXX XXX     XX       XX XXXXXXXXXXX",
        "X      XXXXXX XXX     XX       XX    XX     X",
        "X      XX      XX     XX       XX    XX     X",
        "X      XX      XX     XX       XX           X",
        "X      XX      XX     XX       XX    XX     X",
        "X      XX      XX     XX       XX    XX     X",
        "X      XX      XX     XX       XX    XX     X",
        "X      XX      XX     XX       XX    XX     X",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
      ],
]