const maps = [
    [       
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXYYYYYYYYYXXYYYYYYYYYYYYYYXXYYYYYYYYXXYYYYYYXXXXXXXXX",
        "XXXXXXXXX         XX              XX        XX      XXXXXXXXX",
        "XXXXXXXXX         XX      XX      XX        XX      XXXXXXXXX",
        "XXXXXXXXX         XX      XX      XX        XX      XXXXXXXXX",
        "XXXXXXXXX         XX      XX      XX        XX      XXXXXXXXX",
        "XXXXXXXXX         XX      XY      XX        XX      XXXXXXXXX",
        "XXXXXXXXX         XX      X       XX        XX      XXXXXXXXX",
        "XXXXXXXXX         XXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX",
        "XXXXXXXXX         XXYYYYYYX YYYYYYYYYYY YYYXXYY YYYYXXXXXXXXX",
        "XXXXXXXXXXXXXXXX XXX      X                 XX      XXXXXXXXX",
        "XXXXXXXXXYYYYYYY YXX      XX      XX        XX      XXXXXXXXX",
        "XXXXXXXXX         XX      XX      XX        XX      XXXXXXXXX",
        "XXXXXXXXX         XX      YY      XX        YY      XXXXXXXXX",
        "XXXXXXXXX         XX              XX                XXXXXXXXX",
        "XXXXXXXXX         XX      XX      XX        XX      XXXXXXXXX",
        "XXXXXXXXX         XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXX         XXYYYYYYYXXYY YYYYXXYYYYYYXXYYYYYYXXXXXXXXX",
        "XXXXXXXXXXXX XXXXXXX       XX       XX      XX      XXXXXXXXX",
        "XXXXXXXXXYYY YYYYYXX       XX       XX      XX      XXXXXXXXX",
        "XXXXXXXXX         XX       YY       YY      XX      XXXXXXXXX",
        "XXXXXXXXX         XX                        XX      XXXXXXXXX",
        "XXXXXXXXX         XX       XX       XX      XX      XXXXXXXXX",
        "XXXXXXXXX         XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX",
        "XXXXXXXXX         XXYYYYYYYYXXYY YYYXXYYYYYYXXY YYYYXXXXXXXXX",
        "XXXXXXXXXXXXXXXXX XX        XX      XX      XX      XXXXXXXXX",
        "XXXXXXXXXYYYYYYYY XX        XX      XX      YY      XXXXXXXXX",
        "XXXXXXXXX         XX        XX      YY              XXXXXXXXX",
        "XXXXXXXXX         XX        YY              XX      XXXXXXXXX",
        "XXXXXXXXX         XX                XX      XX      XXXXXXXXX",
        "XXXXXXXXX         XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXX         YYY YYYYYYYYYYYYYYYXXYYYYYXXYYYYYYXXXXXXXXX",
        "XXXXXXXXX                            YY     XX      XXXXXXXXX",
        "XXXXXXXXX         XX          XX            XX      XXXXXXXXX",
        "XXXXXXXXX         XX          XX     XX     XX      XXXXXXXXX",
        "XXXXXXXXXXX XXXXXXXX          XX     XX     XX      XXXXXXXXX",
        "XXXXXXXXXYY YYYYYYXX          XX     XX     XX      XXXXXXXXX",
        "XXXXXXXXX         XX          XX     XX     XX      XXXXXXXXX",
        "XXXXXXXXX         XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX",
        "XXXXXXXXX         XXYYYYYYYYYYXXYYYYYXX YYYYXX YYYYYXXXXXXXXX",
        "XXXXXXXXX         XX          XX     XX     XX      XXXXXXXXX",
        "XXXXXXXXX         XX          XX     XX     XX      XXXXXXXXX",
        "XXXXXXXXX         XX          XX     XX     XX      XXXXXXXXX",
        "XXXXXXXXX         XX          YY     YY     YY      XXXXXXXXX",
        "XXXXXXXXX         XX                                XXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      ],
      [
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "X         XX        XX                      X",
        "X                   XX         XX           X",
        "X         XX        XX         XX           X",
        "X         XX        XX         XX           X",
        "X         XX        XX         XX           X",
        "X         XX        XX         XX           X",
        "X         XX        XX         XX           X",
        "X         XX        XXXXXXXXXXXXXXX XXXXXXXXX",
        "X         XX        XXXXXXXXXXXXXXX XXXXXXXXX",
        "XXXX XXXXXXXX XXXXXXXX         XX           X",
        "XXXX XXXXXXXX XXXXXXXX         XX           X",
        "X         XX        XX         XX           X",
        "X         XX        XX         XX           X",
        "X         XX        XX         XX           X",
        "X         XX        XX         XX           X",
        "X         XX        XX                      X",
        "X         XX        XXXXXXXXX XXXXXXXXXXXXXXX",
        "X         XX        XXXXXXXXX XXXXXXXXXXXXXXX",
        "X         XX        XX         XX           X",
        "XXXXXXXX XXX        XX         XX           X",
        "XXXXXXXX XXX        XX         XX           X",
        "X         XX        XX         XX           X",
        "X         XX        XX         XX           X",
        "X         XX        XX         XX           X",
        "X         XXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXX",
        "X         XXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXX",
        "X         XX        XX         XX           X",
        "X         XX        XX         XX           X",
        "XXXXXXX XXXX        XX         XX           X",
        "XXXXXXX XXXX        XX         XX           X",
        "X         XX        XX         XX           X",
        "X         XX        XX                      X",
        "X         XX           XXXXXX XXXXXXXXXXXXXXX",
        "X         XX        XXXXXXXXX XXXXXXXXXXXXXXX",
        "X         XX XXXXXXXXX        XX            X",
        "X         XX XXXXXXXXX        XX            X",
        "X         XX        XX        XX            X",
        "X         XX        XX        XX            X",
        "X         XX        XX        XX            X",
        "X         XX        XX                      X",
        "X         XX        XX        XX            X",
        "X         XX        XX        XX            X",
        "X         XX        XX        XX            X",
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
      ],
      [
        "XXXXXXXXXXXXXXX",
        "X             X",
        "X    XX  XX   X",
        "X XXXXXX XXXXXX",
        "X XXXXXX XXXXXX",
        "X    XX       X",
        "XXXXXXXXXXXXX X",
        "XXXXXXXXXXXXX X",
        "X      XX     X",
        "X   X  XX   X X",
        "XXX XX    X XXX",
        "XXX XXXXXXX XXX",
        "X      XX     X",
        "X  XX  XX  XX X",
        "XXXXXXXXXXXXXXX"
      ]
]




function export_maps(x) {
    return maps[x]
}